### ISSUE TITLE
Recipe mismatch = Free Fluid

### ISSUE THREAD

**Issue by RighteousPotato** [Argual/Satisfactory-ArgualFluidPressurizer#2]
At the moment, there are two ways of making compressed fluid. Water for example:

- **Compressed Water** - 120 Water /min -> 24 Compressed Water /min
- **Quick Compressed Water** - 240 Pressurized Water /min -> 48 Compressed Water /min

To make the 240 Pressurized Water /min for the "Quick" recipe, you need 1200 Water /min running through 5 Pressure Modulators. Therefore, the standard recipe makes 1 Compressed Water equivalent to 5 Water, whilst the "Quick" recipe makes 1 Compressed Water equivalent to 25 Water.

Abusing this and the relevant decompression recipes, you can generate (Or destroy) fluid from nothing but energy:

- Input 120 Water /min to 1 Pressure Modulator running "Compressed Water", creating 24 Compressed Water /min
- Input that 24 Compressed Water /min to another Pressure Modulator running "Quick Decompressed Water" at 50%, creating 120 Pressurized Water /min
- Input that 120 Pressurized Water /min to another Pressure Modulator running "Depressurized Water" at 250%, creating 600 Water /minute

This multiples your original input by 5, which I am reasonably certain is not the intention of the mod. For what its worth, I personally would simplify things by having just one level of pressurization. If you want to maintain the existing power cost, simply make the recipe take longer.

**Comment by RighteousPotato** [comment]
To make things consistent, the output of the middle step from the readme should be halved:

> _One pressure modulator can process normal fluids into pressurized fluids at 240m³/min (into 48m³/min)._
 **One pressure modulator can process normal fluids into compressed fluids at 120m³/min (into ~~24~~ 12m³/min).**
_One pressure modulator can process pressurized fluids into compressed fluids at 240m³/min (into 120m³/min)._

**Comment by RighteousPotato** [comment]
Or alternatively, the input doubled:

> _One pressure modulator can process normal fluids into pressurized fluids at 240m³/min (into 48m³/min)._
 **One pressure modulator can process normal fluids into compressed fluids at ~~120~~ 240m³/min (into 24m³/min).**
_One pressure modulator can process pressurized fluids into compressed fluids at 240m³/min (into 120m³/min)._

**Comment by RighteousPotato** [comment]
Sorry to spam, but I've spotted something else and also think I've finally understood your intention.

The readme states that pressurized to compressed should go 240->120, in a 2:1 ratio. This seems to be the "Quick" recipes, which currently go 240->48, in a 5:1 ratio.

If you want the shortcut recipes (Normal straight to compressed and back again) to have some cost for its convenience then there should be some loss that applies in both directions. May I suggest:

- Normal to pressurized does a perfect 5:1, 240 to 48
- Pressurized to compressed does a perfect 2:1, 240 to 120
- Normal to compressed attempts the same 10:1 conversion the main recipes achieve but incurs a loss, 240 to 23 (~4% down on what the first two recipes would achieve). Reversing does the same, taking 24 and outputting 230. A full normal->compressed->normal run would take 240 in but only output ~220

**Comment by Argual** [comment]
> To make things consistent, the output of the middle step from the readme should be halved:
> 
> > _One pressure modulator can process normal fluids into pressurized fluids at 240m³/min (into 48m³/min)._
> > **One pressure modulator can process normal fluids into compressed fluids at 120m³/min (into ~24~ 12m³/min).**
> > _One pressure modulator can process pressurized fluids into compressed fluids at 240m³/min (into 120m³/min)._

Indeed, the intent was to output 12 instead of 24, good find. I will deploy the fix shortly.

**Comment by Argual** [comment]
Upon checking them, it seems like I forgot to edit the actual values on the recipes (the assets were made by copying and editing an original asset for pressurized fluid), all recipes were using the 5:1 and 1:5 ratios... oops :D

**Comment by Argual** [comment]
Version out, you can now update to 1.0.2 for the fix.
