### ISSUE TITLE
No output/input

### ISSUE THREAD

**Issue by crashdodgers** [Argual/Satisfactory-ArgualFluidPressurizer#3]
OK, after connecting this to my oil line, I found that the machine was not outputting oil and also the second machine not accepting pressurized oil.

Right, now I have two problems with your machine, 1) Not accepting any input, 2) It does not work with the new Resource Well Pressurizer system, i.e. no output from the pressurizer system on a resource well pipe line and I have a problem of not accepting input of pressurized oil.

Simple put can not be used on resource wells and the depressurizing machine will not accept an input.

The lay out of my two systems is as follows, 1) old/standard oil extraction to a buffer tank, then to a pressurizing machine via mk2 pipe to a mk2 pump up to the station, 2) Resource Well Pressurizer system via mk2 pipe to the refinery for procing.

**Comment by Argual** [comment]
I am not sure I understand what you are trying saying.

It sounds like you are not using the machine correctly.

The machine is intended to compress normal oil into either pressurized or compressed oil directly, or compressing pressurized oil into compressed oil (and vice-versa).

The resource well pressurizer and resource well extractor machines belong to an entirely different system. The "pressurization" terminology is entirely a flavor thing for the mod used to explain why you can turn 10 units of fluid into 1 other fluid and back.

If you are saying that the machine does not accept normal oil when using the pressurized oil or compressed oil recipes, feel free to reopen the issue, but provide a more detailed explanation of your setup and recipes used.

**Comment by crashdodgers** [comment]
I think you are missing the point with the problem here, so I have taken some screenshots to try and help you understand better what is going on.
![Pressurizer System 1](https://github.com/user-attachments/assets/6d8d9df7-4ab7-40da-9c61-af80de8fc954)
![Pressurizer System 1a](https://github.com/user-attachments/assets/9610803c-0718-4635-a61e-1cd2c7b7ada6)
![Pressurizer System 2](https://github.com/user-attachments/assets/9a3fa86a-bf00-4aed-8613-183ed335c2d1)
![Pressurizer System 2a](https://github.com/user-attachments/assets/eb618570-e8c5-4693-8406-43eac245d97e)
![Pressurizing System Map over veiw](https://github.com/user-attachments/assets/aa44e8b2-4fe7-417c-bac1-ac15e7ea2de6)

Right, so lets start, PS1 shows the first pressurizing machine, PS1a shows details of recipe the first pressurizing machine, PS2 shows the second pressurizing machine and the pipe being full, PS2a shows details of recipe the second pressurizing machine and the problem, i.e. no input, PSM is just an interactive map over view of the system configuration.

I hope that you can now understand the problem a bit better.

**Comment by Argual** [comment]
It still seems to me that the error you are experiencing is not the fault of the machine. Just in case, I recreated the relevant parts of your setup to check, and it works fine for me.

![ReproAttempt](https://github.com/user-attachments/assets/503e84ec-3ea7-448d-866a-3b3349f3cf6d)

After I made this picture I noticed you overclocked the machines, and I checked with fully overclocked setup as well, still works.

Ensure that the fluid in the intermediary pipes is pressurized oil in every segment. If you had the setup with normal oil before installing the mod, then you hooked the machines into the existing setup, the pipes may still have normal oil in them, which could explain the issue.

Feel free to send your save file over, but for my convenience please place the hub near the affected machine and maybe place a  beacon as well just to be sure. You can easily and quickly can do this by turning on advanced game settings and creating a new save in creative mode. You can delete the modified save after to resume normal play.
