### ISSUE TITLE
Translation for Korean

### ISSUE THREAD

**Issue by bpforest** [Argual/Satisfactory-ArgualFluidPressurizer#4]
[korean-translations.json](https://github.com/user-attachments/files/17509142/korean-translations.json)

**Comment by Argual** [comment]
Thank you, I will add the translations soon.

**Comment by Argual** [comment]
Translations added, you can update to the new version (1.0.3) to get them in the game.

**Comment by bpforest** [comment]
I think you are hard to see discord message. So, can you provide me updated json that untranslated? (because template json was german)

**Comment by bpforest** [comment]
Oh wait, I confused because someone said in discord, ionized and rocket fuel doesnt added to the mod.

**Comment by Argual** [comment]
ChatGPT and I did as much as we could :D I updated the original template, and here I have the new korean translations for you to edit if you wish. If you would like me to replace the current ones, please reopen this issue.

[korean-translations.json](https://github.com/user-attachments/files/17525709/korean-translations.json)

**Comment by bpforest** [comment]
Do I need to use the ASCII for special characters like original file? (▼, ▽,  , etc.)
Because I'm using python to shorten the task, and when I turn on the ensure_ascii option, Korean is also converted to ASCII code.
+Also it changes Id, so it looks hard to use automation 😔

**Comment by Argual** [comment]
I updated the tool I made for this purpose, you can use the special characters supported in utf-8-bom encoding.

[korean-translations.json](https://github.com/user-attachments/files/17529348/korean-translations.json)
Here is the updated json in case you need it.

**Comment by bpforest** [comment]
[korean-translation.json](https://github.com/user-attachments/files/17529452/korean-translation.json)
Updated strings. btw, should \u202F be written by ASCII?

**Comment by Argual** [comment]
I think it does not matter, tbh. I wouldn't even notice a regular space, but the original english text had the character (not in ASCII). I think when i import it into UE it is fine either way.
