### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Shoenixs** [Argual/Satisfactory-ArgualFluidPressurizer#5]
Hi, I have translated the file for the Russian localization. From the original file, I made the following changes: replaced "H2O" with "water" and "heavy oil residue" with "mazut" according to the Russian localization of the game (there is a comment on line 223 regarding this for future localization updates).
[russian-translations.json](https://github.com/user-attachments/files/17535473/russian-translations.json)
![image](https://github.com/user-attachments/assets/44a5c27a-be82-4f22-acee-b6a59d194131)

**Comment by Argual** [comment]
Thank you, you can now download the new version (1.1.1) with the translations added.
Note: Comments are not kept (and in fact, I have to manually delete them to make the translations importable). The Json file you edit is just a convenient-to-edit medium I use, the translations are not actually stored in this format.

**Comment by Shoenixs** [comment]
I apologize a hundred times, I made a mistake here, I forgot to remove the word "Head". I also changed the wording to something more understandable.
[russian-translations-fix.json](https://github.com/user-attachments/files/17539769/russian-translations-fix.json)
![image](https://github.com/user-attachments/assets/fd41f1d1-44ae-4228-9de5-9ad88353a797)

**Comment by Argual** [comment]
No problem, I updated the mod. You can download the new version (1.1.2) with the fixed translations.
