### ISSUE TITLE
French translated

### ISSUE THREAD

**Issue by kamikaze1723-TM** [Argual/Satisfactory-ArgualFluidPressurizer#6]
Translations for the french language.

[French_translated.json](https://github.com/user-attachments/files/17639425/French_translated.json)

**Comment by Argual** [comment]
Thank you, I added them into the new version (1.2.1).
I had to fix some things and add some missing translations. I uploaded the revised json here for future reference.

[french.json](https://github.com/user-attachments/files/17643250/french.json)
