### ISSUE TITLE
Request: Add support for fluids from Refined Power mod

### ISSUE THREAD

**Issue by Dogmatic** [Argual/Satisfactory-ArgualFluidPressurizer#8]
It would be awesome to be able to use it with these additional liquids.
Love your mod!

**Comment by Argual** [comment]
I'll start working on this, but it may be some time because I am strained for free time ATM. For now I think I will try to make my mod compatible to Refined Power (since you asked) and Ficsit Farming (because I use FF :D )

**Comment by Shad0wlife** [comment]
Thanks for working on this! Managing the steam output of large power plants will be so much nicer with this!

**Comment by Argual** [comment]
Added support for Ficsit Farming and Refined Power. Update to 1.3.0 to get the new version.
