### ISSUE TITLE
fluid pressurizer crash

### ISSUE THREAD

**Issue by rashii46123** [Argual/Satisfactory-ArgualFluidPressurizer#9]
i have tried this 3 times now, every time i go to complete the milestone and hit the launch drone button the game crashes. this is the crash report

Version: 383233, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes, IsSaveGameEdited: No

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038

FactoryGameSteam_FactoryGame_Win64_Shipping!AFGRecipeManager::PopulateAvailableBuildings() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGRecipeManager.cpp:306]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGRecipeManager::AddAvailableRecipe() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGRecipeManager.cpp:218]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGUnlockRecipe::Apply() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Unlocks\FGUnlockRecipe.cpp:37]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGUnlockRecipe::Unlock() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Unlocks\FGUnlockRecipe.cpp:14]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGUnlockSubsystem::OnSchematicPurchased() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGUnlockSubsystem.cpp:176]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGUnlockSubsystem::execOnSchematicPurchased() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGUnlockSubsystem.gen.cpp:398]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_Engine_Win64_Shipping!AActor::ProcessEvent() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1175]
FactoryGameSteam_FactoryGame_Win64_Shipping!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
FactoryGameSteam_FactoryGame_Win64_Shipping!FOnActorRepresentationUpdated_DelegateWrapper() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGActorRepresentationManager.gen.cpp:79]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::GiveAccessToSchematics() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:720]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::GiveAccessToSchematic() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:642]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGUnlockSchematic::Apply() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\Unlocks\FGUnlockSchematic.cpp:13]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGUnlockSubsystem::OnSchematicPurchased() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGUnlockSubsystem.cpp:176]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGUnlockSubsystem::execOnSchematicPurchased() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGUnlockSubsystem.gen.cpp:398]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_Engine_Win64_Shipping!AActor::ProcessEvent() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:1175]
FactoryGameSteam_FactoryGame_Win64_Shipping!TMulticastScriptDelegate<FNotThreadSafeDelegateMode>::ProcessMulticastDelegate<UObject>() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Core\Public\UObject\ScriptDelegates.h:900]
FactoryGameSteam_FactoryGame_Win64_Shipping!FOnActorRepresentationUpdated_DelegateWrapper() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGActorRepresentationManager.gen.cpp:79]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::GiveAccessToSchematics() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:720]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::GiveAccessToSchematic() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:642]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::LaunchShip() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:968]
FactoryGameSteam_FactoryGame_Win64_Shipping!AFGSchematicManager::execLaunchShip() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Intermediate\Build\Win64\FactoryGameSteam\Inc\FactoryGame\UHT\FGSchematicManager.gen.cpp:625]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3110]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3241]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1323]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1055]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::CallFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1167]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3110]
FactoryGameSteam_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1225]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1323]
FactoryGameSteam_CoreUObject_Win64_Shipping!UFunction::Invoke() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6666]
FactoryGameSteam_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2161]
FactoryGameSteam_Engine_Win64_Shipping!FLatentActionManager::TickLatentActionForObject() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:325]
FactoryGameSteam_Engine_Win64_Shipping!FLatentActionManager::ProcessLatentActions() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:233]
FactoryGameSteam_Engine_Win64_Shipping!UWorld::Tick() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1581]
FactoryGameSteam_Engine_Win64_Shipping!UGameEngine::Tick() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1796]
FactoryGameSteam_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:15]
FactoryGameSteam_Win64_Shipping!FEngineLoop::Tick() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5864]
FactoryGameSteam_Win64_Shipping!GuardedMain() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
FactoryGameSteam_Win64_Shipping!GuardedMainWrapper() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
FactoryGameSteam_Win64_Shipping!LaunchWindowsStartup() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
FactoryGameSteam_Win64_Shipping!WinMain() [C:\BuildAgent\work\9fc8da665efb5ffd\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
FactoryGameSteam_Win64_Shipping!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Argual** [comment]
Hi, it is probably connected to my earlier attempts to support Ficsit Farming and Refined Power. You can switch back to previous version until i have time to fix this.

**Comment by Argual** [comment]
Are you using either RP or FF? Is this single player?

**Comment by rashii46123** [comment]
> Are you using either RP or FF? Is this single player?

no, no, and mp / sp, buddy comes in when he can

**Comment by Argual** [comment]
Should work properly now.

**Comment by rashii46123** [comment]
good news, just got in and it works now, no more crashing, thank you :}
